Feature/59340 download rootfs
wirenboard/wb-configs pull request #101
Opened 2023-03-14 16:13 UTC by lostpoint-ru

Add cgi script for rootfs archive on-the-fly generation and download

2023-03-14 20:16 UTC, vdromanov commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +sudo mount /dev/mmcblk0p3 $MOUNT_DIR
у нас же 2 rootfs
кажется, надо бекапить ту, которая сейчас активна

2023-03-14 20:17 UTC, vdromanov commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo umount $MOUNT_DIR
я бы 
umount -f  || true сделал
мало ли что

2023-03-14 20:18 UTC, vdromanov commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    echo 'Content-Disposition: attachment; filename="rootfs.tar.gz"'
мб называть rootfs_серийник?

2023-03-14 20:19 UTC, vdromanov commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +if [ -d "$MOUNT_DIR/etc" ]; then
а почему именно etc?

мб просто проверять, что папка не пустая?

2023-03-14 20:20 UTC, vdromanov commented on debian/changelog
> +  * Add /etc/mosquitto/conf.d/30limits.conf
а это точно не очепятка?

2023-03-14 20:21 UTC, vdromanov commented on configs/etc/nginx/sites-available/default.wb
> +        fastcgi_param SCRIPT_NAME download_rootfs.py;
баш же

2023-03-15 04:54 UTC, lostpoint-ru commented on configs/etc/nginx/sites-available/default.wb
> +        fastcgi_param SCRIPT_NAME download_rootfs.py;
забыл поправить SCRIPT_NAME, да. 

сначала планировалось делать на python, потом вовремя сообразил что это ненужный оверкилл.

поправил.

2023-03-15 04:54 UTC, lostpoint-ru commented on debian/changelog
> +  * Add /etc/mosquitto/conf.d/30limits.conf
упс :) 

поправил

2023-03-15 04:54 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo umount $MOUNT_DIR
сделал

2023-03-15 05:42 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    echo 'Content-Disposition: attachment; filename="rootfs.tar.gz"'
добавил

2023-03-15 05:49 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +sudo mount /dev/mmcblk0p3 $MOUNT_DIR
добавил автоопределение партиции исходя из того что сейчас смонтировано в /

2023-03-15 05:49 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +if [ -d "$MOUNT_DIR/etc" ]; then
хз, мне кажется вообще не принципиально)

2023-03-15 07:28 UTC, vdromanov commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +if [ -d "$MOUNT_DIR/etc" ]; then
лучше всё-таки проверять, что папка не пустая

т.к. выкинем из rootfs /etc - и всё поломается

2023-03-15 07:28 UTC, vdromanov approved these changes
поправить про непустую папку; в остальном - претензий не имею

2023-03-15 10:16 UTC, webconn reviewed
И правда просто. Глянь, не станет ли safari лучше от изменения типа потока.

Ещё предложения: 
 - стоит перемонтировать rootfs как readonly, чтобы нам по дороге мусора не насыпало
 - надо проверить, как это себя поведёт, если tar в середине развалится (можно ли как-то сообщить браузеру, что поток испортился)

2023-03-15 10:16 UTC, webconn commented on configs/etc/sudoers.d/www-data
> +www-data ALL = (root) NOPASSWD: /usr/bin/tar,/usr/bin/mount,/usr/bin/umount
Знатная дырень на будущее получается, конечно. Впрочем, если что, можно будет это переделать на какой-нибудь systemd-сервис потом

2023-03-15 10:16 UTC, webconn commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    echo "Content-Type: application/gzip"
По-моему, из-за этого тебе safari распаковывает сразу. Если тут `application/octet-stream` сделать, не становится лучше?

2023-03-21 07:05 UTC, webconn commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo tar -czf - "$MOUNT_DIR"
Попробовал скачать rootfs с WB7, скорость через провод к середине процесса дошла до 900 КБ/с. Если заменить это на:

```suggestion
    sudo tar -cf - "$MOUNT_DIR" | pigz
```

процесс идёт раза в 3-4 быстрее (просто потому что pigz использует все ядра процессора, а у WB7 их четыре).

Для этого pigz должен быть в зависимостях, естественно

2023-03-21 07:05 UTC, webconn commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo tar -czf - "$MOUNT_DIR"
А ещё после скачивания в архиве обнаружились лишние уровни вложенности:

![image](https://user-images.githubusercontent.com/1550335/226538071-f0870bc7-fc34-43f8-8556-92ac23ee52e3.png)

2023-03-21 07:51 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo tar -czf - "$MOUNT_DIR"
дадада, я помнил про это, в голове была мысль что надо покопаться в флагах tar на предмет исключить часть иерархии, но потом забыл) 

починю.

2023-03-21 09:07 UTC, lostpoint-ru commented on configs/usr/lib/cgi-bin/download_rootfs.sh
> +    sudo tar -czf - "$MOUNT_DIR"
Всё причесал, потестил -- генериться стало в 3-4 раза быстрее, лишней иерархии в архиве нет.

2023-03-23 10:37 UTC, webconn requested changes
Посмотрел ещё раз на архив, обнаружил там непустые `/tmp` и `/var/tmp`. Думаю, стоит исключить.

В целом у меня на этом этапе больше идей нет. Было бы хорошо попробовать добавить архив в FIT и посмотреть, запустится ли система с такого. В любом случае, можно и не сейчас.

2023-03-28 07:04 UTC, merged