udev: add specific tag to WB-internal modems
wirenboard/wb-configs pull request #118
Opened 2023-05-10 08:14 UTC by vdromanov

решили привязать нашему модему специальный тег, чтобы потом дёргать модем по нему
предлагаю тег "wbc"

интересно, что udev имеет доступ к of_compatible и of_name из коробки

проверить можно mmcli -m wbc --set-primary-sim-slot=1

2023-05-10 08:18 UTC, KraPete commented on debian/changelog
> +wb-configs (3.15.4) stable; urgency=medium
```suggestion
wb-configs (3.16.0) stable; urgency=medium
```

2023-05-10 10:13 UTC, KraPete approved these changes
Я, правда, не уверен в названии `wbc`. Может, просто `wb`?

2023-05-11 12:02 UTC, webconn commented
> Я, правда, не уверен в названии `wbc`. Может, просто `wb`?

Я бы не стал, мало ли вдруг у нас какие-то внешние модемы появятся. `wbc` хорошо тем, что на модеме так написано и везде в коде встречается. Можно было бы `wb_internal` сделать или что-то такое, но я не очень понимаю, зачем.

Тут ещё вопрос, как бы сделать так, чтобы пользователю без документации было понятно, что вписать для того, чтобы обратиться к нашему модему; может, обёртку для `mmcli`, которая по умолчанию будет подставлять `-m wbc`? И ещё вопрос, что будет выводить `mmcli -L`, будет ли там написано, что наш модем называется `wbc`

2023-05-11 12:07 UTC, webconn commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +ENV{OF_COMPATIBLE_0}=="wirenboard,wbc-usb", ENV{ID_MM_PHYSDEV_UID}="wbc"
Давай сразу впишем аналогичное для `OF_COMPATIBLE_1-5` условно, а то однажды кто-нибудь добавит в `dts` побольше строк в `compatible` и эта штука молча сломается

2023-05-16 04:06 UTC, KraPete requested changes

2023-05-16 04:06 UTC, KraPete commented on configs/etc/udev/rules.d/99-wb-modem.rules
>  # SIMCOM A7600E-H: SIM switch and mark RNDIS unmanaged for NetworkManager
Надо убрать комментарий про SIM switch

2023-05-16 04:06 UTC, KraPete commented on debian/changelog
> +  * Udev: add specific tag to WB-internal modems
Давай, прямо название тэга нипишем тут

2023-05-16 04:06 UTC, KraPete commented on configs/etc/udev/rules.d/99-wb-modem.rules
>  # QUECTEL EC200T-EU: SIM switch and mark RNDIS unmanaged for NetworkManager
Ещё вот это странный комментарий

2023-05-17 07:42 UTC, vdromanov commented on configs/etc/udev/rules.d/99-wb-modem.rules
>  # SIMCOM A7600E-H: SIM switch and mark RNDIS unmanaged for NetworkManager
готово

2023-05-17 07:42 UTC, vdromanov commented on debian/changelog
> +  * Udev: add specific tag to WB-internal modems
готово

2023-05-17 07:43 UTC, vdromanov commented on configs/etc/udev/rules.d/99-wb-modem.rules
>  # QUECTEL EC200T-EU: SIM switch and mark RNDIS unmanaged for NetworkManager
убрал (думаю, копипаста была)

2023-05-17 07:49 UTC, KraPete commented on debian/changelog
> +  * Udev: add specific tag ("wbc") to WB-internal modems
```suggestion
  * Udev: add ModemManager specific tag ("wbc") to WB-internal modems. mmcli -m wbc could be used to manage the modem
```

2023-05-17 07:49 UTC, KraPete approved these changes

2023-05-17 07:59 UTC, merged