Add fcgiwrap override
wirenboard/wb-configs pull request #141
Opened 2023-10-03 05:51 UTC by KraPete

Prefork 2 fcgiwrap processes

По умолчанию, fcgiwrap обрабатывает только 1 запрос. Если заливать fit и ещё что-то сделать, то второй запрос будет ждать окончания заливки фита

2023-10-03 06:46 UTC, sikmir commented on configs/etc/systemd/system/fcgiwrap.service.d/override.conf
> +ExecStart=/usr/sbin/fcgiwrap -f -c 2
```suggestion
Environment=DAEMON_OPTS=-f -c 2
```

2023-10-03 07:13 UTC, KraPete commented on configs/etc/systemd/system/fcgiwrap.service.d/override.conf
> +ExecStart=/usr/sbin/fcgiwrap -f -c 2
Так не работает

2023-10-03 07:55 UTC, sikmir commented on configs/etc/systemd/system/fcgiwrap.service.d/override.conf
> +ExecStart=/usr/sbin/fcgiwrap -f -c 2
Это странно, понять бы почему, в других сервисах тоже оверрайдим Service/Environment и работает.

2023-10-09 10:52 UTC, vdromanov requested changes
попробовал - чет не заработало (в телегу отписал)

2023-10-10 14:37 UTC, ekateluv approved these changes

2023-10-10 14:38 UTC, ekateluv commented
попробовала, вроде все нормально

2023-10-17 12:36 UTC, lostpoint-ru approved these changes
c wb-mqtt-homeui версии 2.75.12 работает ок

2023-10-24 15:41 UTC, vdromanov approved these changes

2023-10-25 03:33 UTC, merged