support factory-fit immutable attr
wirenboard/wb-configs pull request #181
Opened 2024-09-26 22:37 UTC by vdromanov

игрался с immutable-атрибутом на factory-fit -> перетащил логику в [wb-watch-update](https://github.com/wirenboard/wb-utils/pull/162)

2024-10-01 06:56 UTC, webconn requested changes
мне не нравится решение. насколько я понимаю, оно ломает работу со старыми фитами сразу после обновления через apt.

а если вместо хардлинка делать симлинк, лучше не становилось? да и ради факториресета через web-интерфейс (который делается крайне редко) можно было даже скопировать файл.

2024-10-01 06:56 UTC, webconn commented on configs/usr/lib/cgi-bin/factory_reset.py
> +    USE_FACTORY_FIT_FLAG = "%swb_use_factory_fit.flag" % RW_DIR
решение с os.path.join для объединения путей лучше читается, но это в целом на будущее

2024-10-03 12:33 UTC, vdromanov commented on configs/usr/lib/cgi-bin/factory_reset.py
> +    USE_FACTORY_FIT_FLAG = "%swb_use_factory_fit.flag" % RW_DIR
готово

2024-10-04 10:14 UTC, webconn approved these changes

2024-10-07 21:13 UTC, merged