Добавление www-data в группу mosquitto перед запуском сервиса fcgiwrap
wirenboard/wb-configs pull request #184
Opened 2024-10-20 16:02 UTC by taraant

Добавил команду в override сервиса fcgiwrap добавляющую пользователя www-data в группу mosquitto перед запуском сервиса fcgiwrap

2024-10-20 16:14 UTC, lostpoint-ru reviewed
Версию в changelog еще надо поднять :)

2024-10-21 04:39 UTC, KraPete requested changes
Присоединяюсь к Саше

2024-10-21 07:46 UTC, vdromanov commented
1) универсальные штуки вроде такого можно ставить прям на группу "developers"
2) есть пока не утверждённый (и не доделанный) [инструктион](https://docs.google.com/document/d/1nfp3tMF450yco-DMwgQBPTrD-gRrpKtjcJh1peXBG6Q/edit?tab=t.0) - с ним надо бы ознакомиться: там про чейнжлог тоже есть

2024-10-21 13:17 UTC, closed without merging

2024-10-21 13:49 UTC, taraant commented
спасибо. 
создал новый PR по рекомендациям https://github.com/wirenboard/wb-configs/pull/185