Logging improvement in Stretch
wirenboard/wb-configs pull request #39
Opened 2021-01-11 14:51 UTC by PeteK12

* journald persistent logging is enabled
  * busybox-syslogd is replaced by rsyslog.
    Log archive is limited to 20MB. Log rotation is implemented using rsyslog's outchannel.

2021-01-12 07:47 UTC, evgeny-boger requested changes

2021-01-12 07:47 UTC, evgeny-boger commented on configs-stretch/usr/bin/wb-rsyslog-rotation
> +#!/bin/bash
если бинарник не для пользователя, то его не надо в /usr/bin, лучше положить в /usr/lib

2021-01-12 07:47 UTC, evgeny-boger commented on configs-stretch/etc/watchdog.conf.wb
> +pidfile		= /var/run/rsyslogd.pid
это не нужно, весь блок - дикое легаси.
Стоит просто убрать строчку про syslog здесь

2021-01-12 07:47 UTC, evgeny-boger commented on configs-stretch/etc/systemd/journald.conf.wb
> +Storage=persistent
а какие настройки этого persistent? Нам же тоже нужно здесь ограничить логи по размеру

2021-01-12 08:08 UTC, PeteK12 commented on configs-stretch/etc/systemd/journald.conf.wb
> +Storage=persistent
10% от размера фс.
https://www.freedesktop.org/software/systemd/man/journald.conf.html#SystemMaxUse=

Задать явно какое-то значение?

2021-01-12 08:11 UTC, PeteK12 commented on configs-stretch/usr/bin/wb-rsyslog-rotation
> +#!/bin/bash
Перенёс

2021-01-12 08:12 UTC, PeteK12 commented on configs-stretch/etc/watchdog.conf.wb
> +pidfile		= /var/run/rsyslogd.pid
Убрал

2021-02-24 00:33 UTC, evgeny-boger reviewed
По-моему раскраска из вывода journalctl попадает в логи в битом виде, а не выкидывается:

```
Feb 24 00:17:20 wirenboard-AYSDI5ZH systemd[1]: Stopping Flush Journal to Persistent Storage...
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[32mZigbee2MQTT:info #033[39m 2021-02-24 00:17:20: Starting Zigbee2MQTT version 1.15.0 (
commit #unknown)
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[32mZigbee2MQTT:info #033[39m 2021-02-24 00:17:20: Starting zigbee-herdsman...
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[31mZigbee2MQTT:error#033[39m 2021-02-24 00:17:24: Error while starting zigbee-herdsman
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[31mZigbee2MQTT:error#033[39m 2021-02-24 00:17:24: Failed to start zigbee
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[31mZigbee2MQTT:error#033[39m 2021-02-24 00:17:24: Exiting...
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]: #033[31mZigbee2MQTT:error#033[39m 2021-02-24 00:17:24: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyMOD3'
Feb 24 00:17:25 wirenboard-AYSDI5ZH npm[17758]:     at Znp.<anonymous> (/mnt/data/root/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
```

@PeteK12 посмотри пожалуйста, если это сложно исправлять - вольём без этого, если несложно - стоит исправить.

2021-02-24 03:56 UTC, PeteK12 commented
@evgeny-boger Это в /var/log/messages?

2021-02-24 06:02 UTC, webconn commented
Github ещё ругается на отсутствие newline в конце некоторых файлов, давай добавим их

2021-02-24 07:04 UTC, PeteK12 commented on configs-stretch/etc/systemd/journald.conf.wb
> +Storage=persistent
Основной journald. rsyslog только для тех, кто привык к `cat /var/log/messages | grep`.

2021-02-24 07:37 UTC, webconn commented on configs-stretch/etc/systemd/journald.conf.wb
> +Storage=persistent
Штош, это неизящно, но похоже на решение. Надо как-то переучивать пользователей, я думаю.
Не прямо сейчас, но для дискуссии: может, придумать способ выводить в консоль что-нибудь вроде `попробуйте делать то же самое через journalctl`, если пользователь вызвал что-то с `/var/log/messages`?

2021-02-24 07:38 UTC, webconn approved these changes
Попробуй ещё разобраться с раскраской (то, что Женя написал), а в остальном ок

2021-02-24 07:40 UTC, webconn commented
Кстати, я считаю, что пора вводить практику сливать коммиты в один перед мержем в мастер, а то у нас история слишком пёстрая и в ней сложно ориентироваться.

2021-02-24 07:42 UTC, PeteK12 commented
Нажать на стрелочку у "Merge pull request" и выбрать "Squash and merge"?

2021-02-24 07:46 UTC, webconn commented
О, не знал, что гитхаб так умеет.
Да, как-то так.

2021-02-24 10:31 UTC, PeteK12 commented
@evgeny-boger @webconn Сделал, чтобы непечатные символы не экранировались. Теперь они пишутся в лог, и при выводе в консоль сообщения раскарашиваются.

2021-02-24 10:31 UTC, evgeny-boger commented
bq. Кстати, я считаю, что пора вводить практику сливать коммиты в один перед мержем в мастер, а то у нас история слишком пёстрая и в ней сложно ориентироваться.

Ну это очень спорно. История после вливания должна быть нормальная, но это не значит, что нужно делать squash на всё не глядя. В больших сложных фичах лучше отребейзить историю перед PR и перед вливанием, чтобы коммиты были большие и осмысленные.
Стандартный критерий: мастер собирается и работает после каждого коммита.

2021-02-24 10:33 UTC, evgeny-boger commented
>@evgeny-boger Это в /var/log/messages?

ага. В journalctl посмотрел этот же кусок глазами, там действительно есть выделение то ли жирным, то ли более белым. В общем с эскейп-последовательностями, которые потом в логе и осели.

2021-02-24 10:36 UTC, evgeny-boger commented on configs-stretch/etc/systemd/journald.conf.wb
> +Storage=persistent
>Надо как-то переучивать пользователей, я думаю.

как внедрим, будем всю документацию переписывать и анонс сделаем.

>способ выводить в консоль
мне кажется, оно всё как-то уж очень инвазивно будет. Может просто при ротации или периодически в  /var/log/messages выводить строчку про это? Кто-нибудь заметит.

2021-02-24 10:40 UTC, merged

2021-02-24 11:29 UTC, webconn commented
> > Кстати, я считаю, что пора вводить практику сливать коммиты в один перед мержем в мастер, а то у нас история слишком пёстрая и в ней сложно ориентироваться.
> 
> Ну это очень спорно. История после вливания должна быть нормальная, но это не значит, что нужно делать squash на всё не глядя. В больших сложных фичах лучше отребейзить историю перед PR и перед вливанием, чтобы коммиты были большие и осмысленные.
> Стандартный критерий: мастер собирается и работает после каждого коммита.

Ну да, ребейзим и сливаем коммиты, потом мержим в мастер. Стандартный критерий выполняется, у тебя как раз получается большой коммит, который выходил из (работающего) мастера и стал (работающим) мастером. Плюс, вся твоя работа представлена одним коммитом и при необходимости его можно черрипикнуть куда-нибудь в другое место истории (само собой, не всегда без конфликтов, но у одного коммита это решать иногда сильно проще, чем у последовательности).

Ессно, не делать этого бездумно: если слишком важно разделить на несколько коммитов - делим, но это должно быть исключением.

2021-02-24 11:45 UTC, evgeny-boger commented
Я для себя два критерия выделяю, когда лучше отдельные коммиты:

1) они имеют ценность по-отдельности.Т.е. может понадобится откатить только части или перенести только часть. 
2) Когда PR целиком читать и осознавать больше пяти минут. Сложную функциональность проще ревьювить по логическим частям. А значит и потом, если придётся рыться в истории, то будет удобнее по частям.

2021-02-24 12:28 UTC, webconn commented
Справедливо. Судя по истории, в последнее время так и происходит, так что просто продолжаем придерживаться этого курса.

И не забываем ребейзиться. Если будем всё это делать, у нас не будет возникать ситуаций, подобных этой:
![Screenshot_20210224_152709](https://user-images.githubusercontent.com/1550335/109000532-e26e4380-76b4-11eb-8374-98b426232787.png)