Added mount point /tmp to chroot_this script
wirenboard/wb-configs pull request #61
Opened 2022-08-17 19:42 UTC by rkochkin

Добавил монтирование /tmp для нормальной работы apt в chroot окружении.

2022-08-18 10:38 UTC, KraPete requested changes
Мне ещё пришлось смонтировать

/dev/random
/dev/urandom
/dev/zero
/dev/full
/dev/null

2022-08-18 13:24 UTC, rkochkin commented
> Мне ещё пришлось смонтировать
> 
> /dev/random /dev/urandom /dev/zero /dev/full /dev/null

/dev/null есть в rootfs, только его нужно переделать на символьное устройство.
@KraPete А для чего возникла необходимость в 
/dev/random
/dev/urandom
/dev/zero
/dev/full

2022-08-22 10:37 UTC, webconn requested changes

2022-08-22 10:37 UTC, webconn commented on configs/chroot_this.sh
> +mount --bind /dev/random $DIR/dev/random
Я бы делал это для режима песочницы, как в этом скрипте: https://gist.github.com/schnell18/7287068#file-create_chrootjail-sh-L28

Так не надо будет umount делать в тысяче мест и ничего не потеряется

2022-08-24 11:03 UTC, rkochkin commented on configs/chroot_this.sh
> +mount --bind /dev/random $DIR/dev/random
@webconn @KraPete 
У меня не создавались /tmp  и символьные устройства, потому что не до конца распаковывался архив. Если распаковывать архив под рутом, то и символьные устройства создаются и /tmp и нормально чрутится скриптом, который в master

2022-08-24 11:38 UTC, KraPete commented on configs/chroot_this.sh
> +mount --bind /dev/random $DIR/dev/random
Тогда ничего не трогаем и всё

2022-11-22 11:16 UTC, rkochkin commented
Закрываю PR. apt в chroot окружении работает без этого изменения

2022-11-22 11:16 UTC, closed without merging