Add ModemManager support
wirenboard/wb-configs pull request #63
Opened 2022-08-25 05:38 UTC by KraPete

2022-08-25 15:14 UTC, evgeny-boger commented on configs/etc/NetworkManager/system-connections/wb-gsm.nmconnection
> +id=wb-gsm
у нас же их потом будет 2 разных для разных симок, правильно? Может сразу назвать как-нибудь типа wb-gsm-sim1?

2022-08-26 06:06 UTC, KraPete commented on configs/etc/NetworkManager/system-connections/wb-gsm.nmconnection
> +id=wb-gsm
Переименовал

2022-09-05 11:00 UTC, webconn requested changes

2022-09-05 11:00 UTC, webconn commented on debian/wb-configs.wb-gsm.service
> +Environment=DEBUG=1
надо отключить?

2022-09-05 11:46 UTC, KraPete commented on configs/etc/NetworkManager/system-connections/wb-eth0.nmconnection
> +dhcp-hostname=WirenBoard
Да. Но у нас в дефолтном `/etc/netwrok/interfaces` сделано так:
```
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
   pre-up wb-set-mac
   hostname WirenBoard

allow-hotplug eth1
iface eth1 inet dhcp
   pre-up wb-set-mac
   hostname WirenBoard
```
Потому и тут прописал.

2022-09-05 11:47 UTC, KraPete commented on debian/wb-configs.wb-gsm.service
> +[Unit]
Я исходил из того, что в этом пакете все настройки, которые чистый debian в WB превращают, потому тут и  место сервису.

2022-09-05 11:50 UTC, webconn commented on debian/wb-configs.wb-gsm.service
> +Environment=DEBUG=1
Если он не нужен в обычной жизни, да. То есть, проверить, что меняется от этого флага, и если без него можно различить, что происходит, то убрать. А если нельзя, то это назревшее изменение в wb-gsm :)

2022-09-05 11:50 UTC, KraPete commented on debian/wb-configs.wb-gsm.service
> +Environment=DEBUG=1
Отключил

2022-09-05 11:50 UTC, KraPete commented on configs/etc/NetworkManager/system-connections/wb-eth0.nmconnection
> +dhcp-hostname=WirenBoard
Убрал

2022-09-05 11:50 UTC, webconn commented on configs/etc/NetworkManager/system-connections/wb-eth0.nmconnection
> +dhcp-hostname=WirenBoard
Думаю, не нужно, в interfaces оно тоже заехало как-то от балды

2022-09-05 11:51 UTC, webconn commented on debian/wb-configs.wb-gsm.service
> +[Unit]
Но тут самого wb-gsm нет, так что лучше перенести. Тут именно конфиги, без вспомогательного софта

2022-09-05 11:59 UTC, KraPete commented on debian/wb-configs.wb-gsm.service
> +[Unit]
Перенёс

2022-09-06 07:28 UTC, webconn approved these changes

2022-09-19 10:56 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-configs/pull/65

2022-09-19 10:56 UTC, closed without merging