Auto-mount MicroSD to /mnt/sdcard
wirenboard/wb-configs pull request #78
Opened 2022-12-19 11:46 UTC by sikmir

2022-12-23 09:20 UTC, wb-adegtyarev approved these changes
Проверил на Wiren Board 7.3.1 staging.06686.cf98af374eb4 (as testing):

1. Поставил пакет, вставил карту — не работает. Вытащил карту.
2. Перезапустил контроллер командой reboot. Вставил карту, создался каталог /mnt/sdcard и появилось содержимое карты.
3. Вытащил карту, каталог остался, содержимое пропало. Выключил контроллер выключателем.
4. Вставил карту, включил контроллер, в каталоге /mnt/sdcard появилось содержимое карточки.

2022-12-23 13:21 UTC, sikmir commented
> Проверил на Wiren Board 7.3.1 staging.06686.cf98af374eb4 (as testing):
> 
>     1. Поставил пакет, вставил карту — не работает. Вытащил карту.
> 
>     2. Перезапустил контроллер командой reboot. Вставил карту, создался каталог /mnt/sdcard и появилось содержимое карты.
> 
>     3. Вытащил карту, каталог остался, содержимое пропало. Выключил контроллер выключателем.
> 
>     4. Вставил карту, включил контроллер, в каталоге /mnt/sdcard появилось содержимое карточки.

Сценарий 2 не должен работать, карточка автоматически монтируется только при загрузке.

2022-12-23 17:45 UTC, evgeny-boger requested changes
хотелось бы конечно автоматически.
добавление 
x-systemd.automount не решит проблему?

2022-12-23 17:46 UTC, wb-adegtyarev commented
> Сценарий 2 не должен работать, карточка автоматически монтируется только при загрузке.

Что делаем? Работает же.

2022-12-23 17:46 UTC, evgeny-boger commented
ещё хорошо бы это проверить с fat, exfat, ntfs. Флешки с ними бывают.

2022-12-23 18:27 UTC, wb-adegtyarev commented
> ещё хорошо бы это проверить с fat, exfat, ntfs. Флешки с ними бывают.

Я вот так проверял, в FAT32 и NTFS форматировали на Windows 10, а в FAT16 уже под Linux.

![ksnip_20221223-222524](https://user-images.githubusercontent.com/77433258/209391586-3ed80213-d063-4c60-a19e-284d6dccddb1.png)
![ksnip_20221223-221343](https://user-images.githubusercontent.com/77433258/209391588-c74f6293-0be3-47d1-a606-401f6db019cd.png)
![ksnip_20221223-220521](https://user-images.githubusercontent.com/77433258/209391590-2dd2b8fd-5209-4bf1-9fc8-e6fe568fe763.png)

2022-12-23 18:33 UTC, sikmir commented
> хотелось бы конечно автоматически. добавление x-systemd.automount не решит проблему?

O, systemd так умеет. Да, работает.

2022-12-26 21:56 UTC, sikmir commented
Without microSD:
```sh
# time ls /mnt
ls: cannot access '/mnt/sdcard': No such device
data/  sdcard/

________________________________________________________
Executed in    2.26 secs   fish           external
   usr time   19.77 millis    4.68 millis   15.08 millis
   sys time    2.39 millis    2.39 millis    0.00 millis
```

With microSD:
```sh
# time ls /mnt
data/  sdcard/

________________________________________________________
Executed in  312.95 millis    fish           external
   usr time   14.55 millis    4.70 millis    9.85 millis
   sys time    8.11 millis    2.44 millis    5.67 millis
```

2022-12-27 08:43 UTC, evgeny-boger approved these changes

2022-12-27 08:43 UTC, merged