Move default NetworkManager connections to /usr/lib
wirenboard/wb-configs pull request #80
Opened 2022-12-23 07:04 UTC by KraPete

2022-12-23 07:09 UTC, sikmir commented on debian/wb-configs.postinst
> +        local connection_hashes=("d99be5a51292b10e558a37d5766c8859"  # wb-eth0.nmconnection
Не забыть бы теперь при правке nmconnection обновлять хеши.

2022-12-23 07:24 UTC, KraPete commented on debian/wb-configs.postinst
> +        local connection_hashes=("d99be5a51292b10e558a37d5766c8859"  # wb-eth0.nmconnection
Не надо. Теперь всё в `/usr/lib` и обновляется автоматом, т.к. не считается пользовательским конфигом. Хэши тут нужны только, чтобы старые конфиги по умолчанию из `/etc` грохнуть.

2022-12-23 07:26 UTC, webconn requested changes

2022-12-23 07:26 UTC, webconn commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +sed -i "s/^ssid=@SSID@$/ssid=${ssid}/" "/usr/lib/NetworkManager/system-connections/wb-ap.nmconnection"
Вообще говоря это плохо, лучше оверлей сделать в /etc. Однажды мы захотим параметры по умолчанию какие-нибудь подкрутить в оригинальном файле, и придётся сложно сравнивать файлы. А ещё файл подкручивать придётся на каждом обновлении

2022-12-23 07:26 UTC, webconn commented on debian/wb-configs.postinst
> +        local connection_hashes=("d99be5a51292b10e558a37d5766c8859"  # wb-eth0.nmconnection
А это не понадобится, эти хеши про нынешнее состояние соединений, пока они в etc. Кажется, это стоит сдобрить комментарием

2022-12-23 07:26 UTC, webconn commented on debian/wb-configs.postinst
>          rm -f /etc/NetworkManager/conf.d/wb.conf || true
Надо бы это тоже хешем защитить, мало ли кто туда ручонками полезет

2022-12-23 07:26 UTC, webconn commented on debian/wb-configs.postinst
> +            sed -i "/${ssid2}/d" $tmp_connection
```suggestion
            local ssid_regexp="Wiren[Bb]oard-${short_sn}"
            # remove default SSID value as it is device specific ad affects md5 hash
            sed -i "/${ssid_regexp}/d" $tmp_connection
```

Или ещё проще

```suggestion
            local ssid="WirenBoard-${short_sn}"
            # remove default SSID value as it is device specific ad affects md5 hash
            sed -i "/${ssid}/di" $tmp_connection
```

2022-12-23 07:31 UTC, KraPete commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +sed -i "s/^ssid=@SSID@$/ssid=${ssid}/" "/usr/lib/NetworkManager/system-connections/wb-ap.nmconnection"
Не понял, про что ты.

2022-12-23 07:33 UTC, KraPete commented on debian/wb-configs.postinst
>          rm -f /etc/NetworkManager/conf.d/wb.conf || true
Тоже не совсем понял зачем. Оно лежит в `/usr/lib` и не предполагает редактирование пользователем. Для пользователя есть `/etc`

2022-12-23 07:42 UTC, webconn commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +sed -i "s/^ssid=@SSID@$/ssid=${ssid}/" "/usr/lib/NetworkManager/system-connections/wb-ap.nmconnection"
Редактировать файлы в `/usr` поперёк пакетного менеджера - плохо. В моём представлении `/usr` вообще должен уметь становиться readonly без потери в функциональности (кроме установки/удаления пакетов, конечно).

Если у нас есть что-то генерируемое, для этого есть `/var` или `/etc` в крайнем случае. Из `/var/lib` NetworkManager список соединений не читает, к сожалению, потому остаётся `/etc`.

NetworkManager умеет собирать параметры для соединения, открывая файл сначала в `/usr/lib`, потом в `/etc`, так работает редактирование системных соединений

2022-12-23 07:43 UTC, webconn commented on debian/wb-configs.postinst
>          rm -f /etc/NetworkManager/conf.d/wb.conf || true
Это да, просто если кто-то решит в `/etc` сделать файл с таким именем, он будет при обновлении удаляться без причины

2022-12-23 08:06 UTC, KraPete commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +sed -i "s/^ssid=@SSID@$/ssid=${ssid}/" "/usr/lib/NetworkManager/system-connections/wb-ap.nmconnection"
Т.е. ты предлагаешь положить в `/usr` шаблон. После установки сделать подстановку и, если в `/etc` неизменённый файл, заменить его на вновь сгенерированный? В результате надо будет хэши на каждый чих хранить

2022-12-28 11:20 UTC, webconn commented
Созвонились, подумали, как с этим быть, решили вот что:

 - соединение wb-ap лежит в виде шаблона в /usr вместе с остальными соединениями (с плейсхолдером вместо названия точки доступа)
 - при установке wb-configs и в wb-prepare вызывается скрипт, который создаёт wb-ap в /etc из шаблона, только если в /etc не было этого соединения (или симлинка на /dev/null, который появляется при удалении соединения)
 - при установке wb-configs при сборке rootfs не надо создавать соединение в /etc (это можно сделать через systemd-сервис, или перед стартом networkmanager)
 - соглашаемся на то, что правки в шаблон wb-ap будут фактически применяться только при factory reset

2022-12-29 10:17 UTC, webconn requested changes

2022-12-29 10:17 UTC, webconn commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +deleted_wb_ap="/etc/NetworkManager/system-connections/d12c8d3c-1abe-4832-9b71-4ed6e3c20885.nmmeta"
```suggestion
wb_ap_uuid=$(awk -F '=' '$1=="uuid" {print $2}' /usr/lib/NetworkManager/system-connections/wb-ap.nmconnection)
deleted_wb_ap="/etc/NetworkManager/system-connections/${wb_ap_uuid}.nmmeta"
```

Чтобы меньше хардкода таскать

2022-12-29 10:17 UTC, webconn commented on debian/wb-configs.postinst
> +#!/bin/bash
Это копипаста? Внезапный шебанг

2022-12-29 10:17 UTC, webconn commented on debian/wb-configs.postinst
>          rm -f /etc/NetworkManager/conf.d/wb.conf || true
Это всё ещё актуально

2022-12-29 10:17 UTC, webconn commented on debian/wb-configs.postinst
> +            rm -f $2 || true
Я бы тут ещё в лог выводил, что мы подчищаем старый файл

2022-12-29 10:17 UTC, webconn commented on debian/wb-configs.postinst
> +    for cn_hash in ${ar[@]}; do
Что-то это жутковато получается, метабаш какой-то. Идеально было бы сюда один хеш передавать и сделать перебор как тут: https://www.cyberciti.biz/faq/finding-bash-shell-array-length-elements/

2022-12-29 10:27 UTC, KraPete commented on configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh
> +deleted_wb_ap="/etc/NetworkManager/system-connections/d12c8d3c-1abe-4832-9b71-4ed6e3c20885.nmmeta"
Переделал

2022-12-29 10:28 UTC, KraPete commented on debian/wb-configs.postinst
> +#!/bin/bash
Ага. Убрал

2022-12-29 10:30 UTC, KraPete commented on debian/wb-configs.postinst
> +            rm -f $2 || true
Добавил

2022-12-29 10:48 UTC, KraPete commented on debian/wb-configs.postinst
> +    for cn_hash in ${ar[@]}; do
Переделал это место

2022-12-29 10:56 UTC, webconn commented on debian/wb-configs.postinst
> +                        echo "Removing old default connection $cn"
```suggestion
                        echo "Removing old default connection $cn"
                        rm -f $cn || true
```

2022-12-29 10:56 UTC, webconn commented on debian/wb-configs.postinst
> +                echo "Removing old $old_wb_conf"
```suggestion
                echo "Removing old $old_wb_conf"
                rm -f $old_wb_conf || true
```

2022-12-29 11:06 UTC, webconn approved these changes

2022-12-29 14:20 UTC, sikmir commented on debian/wb-configs.postinst
> +    for cn_hash in ${ar[@]}; do
Кстати башовые скриптики еще полезно с помощью `shellcheck` проверять

2022-12-29 14:25 UTC, sikmir approved these changes

2022-12-30 06:58 UTC, merged