migrate usb-network params from wb-utils
wirenboard/wb-configs pull request #88
Opened 2023-01-11 12:58 UTC by vdromanov

перетащил NM-настроечки вокруг usb-network из wb-utils

2023-01-11 13:09 UTC, webconn commented on debian/wb-configs.postinst
> +            if [ "$wb_conf_calculated_hash" == "33393d5bcc60b520d94bfb0eb4535ed5" ]; then
Тут хеш для контроллеров, на которых совсем старый конфиг стоял. Это хеш не от актуального конфига, а чтобы смигрировать со старой версии wb-configs. В общем, не надо менять

2023-01-11 13:33 UTC, webconn requested changes
Хеш надо вернуть как было. В остальном, кажется, работает. На Thinkpad X1 yoga gen2 не заводится со встроенных USB (ни с type c, ни с 3.0), через хаб или докстанцию работает лучше, через 2.0 порты вообще проблем не было. Но это вроде как аппаратная проблема, или что-то в драйверах в ядре, тут мы ничего уже не сделаем запросто.

2023-01-12 15:33 UTC, vdromanov commented on debian/wb-configs.postinst
> +            if [ "$wb_conf_calculated_hash" == "33393d5bcc60b520d94bfb0eb4535ed5" ]; then
упс, готово

2023-01-12 15:34 UTC, vdromanov commented on debian/wb-configs.postinst
> +            if [ "$wb_conf_calculated_hash" == "33393d5bcc60b520d94bfb0eb4535ed5" ]; then
упс, готово

2023-01-17 09:52 UTC, webconn approved these changes

2023-01-17 10:04 UTC, merged