mosquitto: log to syslog instead of file
wirenboard/wb-configs pull request #89
Opened 2023-01-11 14:53 UTC by sikmir

2023-01-11 16:22 UTC, webconn requested changes

2023-01-11 16:22 UTC, webconn commented on configs/etc/wb-configs.d/01wb-configs
> +wb_move /etc/mosquitto/mosquitto.conf
Вот это не даст нам потом ничего поправить в базовом конфиге без ухищрений в скриптах. А ещё эта штука не дружит с displace, потому что `/etc/mosquitto/mosquitto.conf` после displace - симлинк на `mosquitto.conf.wb`. В общем, предлагаю сюда не добавлять.

2023-01-11 16:42 UTC, webconn approved these changes

2023-01-11 16:44 UTC, KraPete commented
Т.е. мы сейчас хрясь и всем снесём настройки бриджей и прочего?

2023-01-11 16:45 UTC, webconn commented
> Т.е. мы сейчас хрясь и всем снесём настройки бриджей и прочего?

Если кто-то их в `mosquitto.conf` настраивал, то да, кстати. Мы вроде под бриджи отдельные конфиги делали

2023-01-11 16:46 UTC, sikmir commented
> Т.е. мы сейчас хрясь и всем снесём настройки бриджей и прочего?

Нет, бриджи должны не в mosquitto.conf быть, хотя такое тоже может быть.

2023-01-11 16:47 UTC, webconn commented
А если про лог написать в `conf.d`, это будет не вместо предыдущего, а вместе с предыдущим, так?

2023-01-11 22:57 UTC, sikmir commented
> А если про лог написать в `conf.d`, это будет не вместо предыдущего, а вместе с предыдущим, так?

Да, будет в оба тогда.

2023-01-12 06:29 UTC, webconn commented
А может тогда через `transform` сделаем? https://manpages.debian.org/testing/config-package-dev/dh_configpackage.1.en.html

2023-01-13 06:48 UTC, sikmir commented
> А может тогда через `transform` сделаем? https://manpages.debian.org/testing/config-package-dev/dh_configpackage.1.en.html

Сделал через `transform`:

2023-01-13 06:53 UTC, KraPete commented on debian/control
> +Build-Depends: debhelper (>= 10), config-package-dev (>= 5.0), mosquitto (>= 1.4.7-1)
А зачем москита? @webconn это ничего не сломает?

2023-01-13 06:55 UTC, sikmir commented on debian/control
> +Build-Depends: debhelper (>= 10), config-package-dev (>= 5.0), mosquitto (>= 1.4.7-1)
Нам нужен конфиг в момент сборки.

2023-01-13 06:57 UTC, webconn commented on debian/control
> +Build-Depends: debhelper (>= 10), config-package-dev (>= 5.0), mosquitto (>= 1.4.7-1)
Ой, а я думал, что transform делается на машине, куда устанавливается пакет, а не на сборочной. Если на сборочной, то всё это как-то не имеет смысла

2023-01-13 07:03 UTC, sikmir commented on debian/control
> +Build-Depends: debhelper (>= 10), config-package-dev (>= 5.0), mosquitto (>= 1.4.7-1)
По крайней мере это лучше displace тем, что не надо целиком mosquitto.conf тащить в wb-configs. Еще как вариант в post install у wb-configs делать замену в конфиге, но тоже как-тот такое..

2023-01-13 10:33 UTC, sikmir commented
На митинге решили пока не вливать.

2023-06-05 18:04 UTC, webconn commented on debian/wb-configs.postinst
> +    deb-systemd-invoke restart mosquitto
Это лучше делать при условии, что файл поменялся, у нас сейчас есть сервисы, которым это может не понравиться

2023-06-05 18:34 UTC, webconn approved these changes

2023-06-05 19:17 UTC, merged