add udev rule to ignore old wb-modems: sim800, sim800c-ds, sim5300e, …
wirenboard/wb-configs pull request #91
Opened 2023-01-25 07:51 UTC by vdromanov

…sim7000e

нашел разных модемов; повтыкал в WB7
c этим правилом mmcli --list-modems их не видит

порисёчил, можно ли сделать что-то похитрее vid/pid - кажется, что нет

на wb67 - пока не гонял

2023-01-25 07:54 UTC, vdromanov commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +# QUECTEL EC200T-EU: SIM switch and mark RNDIS unmanaged for NetworkManager
кажется, мы квиктел когда-то продавали, как WBC-4G (уточню)

если так - надо в MM поддержать :(

2023-01-25 12:04 UTC, webconn requested changes

2023-01-25 12:04 UTC, webconn commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +SUBSYSTEMS=="tty", SYMLINK="ttyGSM", ENV{ID_MM_DEVICE_IGNORE}="1"
Если не ошибаюсь, такое правило должно навешать симлинк ttyGSM на все терминалы (SYMLINK не сравнивается, а присваевается). А ещё у этого файла такой же номер, как у `99-wb-uart.rules`, так что оно раньше `uart` по чистой случайности. Я бы сходил во все `wb-uart.rules`, где определён `ttyGSM` и там явно бы прописал игнор.

2023-01-25 12:04 UTC, webconn commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +SUBSYSTEMS=="usb", ATTRS{idVendor}=="1e0e|2c7c|0e8d", GOTO="wb_usb_modem_types"
Думаю, надо `idVendor` отсюда убирать, пусть ниже явно сравнивается. Чтобы копипасты не было

2023-01-25 14:11 UTC, vdromanov commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +SUBSYSTEMS=="usb", ATTRS{idVendor}=="1e0e|2c7c|0e8d", GOTO="wb_usb_modem_types"
готово

2023-01-25 14:11 UTC, vdromanov commented on configs/etc/udev/rules.d/99-wb-modem.rules
> +SUBSYSTEMS=="tty", SYMLINK="ttyGSM", ENV{ID_MM_DEVICE_IGNORE}="1"
да, недоглядел; вылезло в проверке


готово

2023-01-25 14:11 UTC, vdromanov commented
погонял на wb6x + sim5300e; wb67 + sim800; wb67 + sim7000e

2023-01-25 15:20 UTC, webconn reviewed
lgtm

2023-01-31 12:26 UTC, webconn approved these changes

2023-01-31 21:26 UTC, merged